a = int(1)
b = int(2.8)
c = int("3")
print("Example of Casting 1 : ")
print(a)    
print(b)
print(c)

x = float(1)
y = float(2.8)
z = float("3")
print("\nExample of Casting 2 : ")
print(x)
print(y)    
print(z)